map $status $log_backend_down {
    ~^50 1;
    default 0;
}

# log
log_format backend_down 
    '$remote_addr [$time_local]'
    '"$request" $status'
    'upstream=$upstream_addr'
    'error="$upstream_status"';

    server {
        listen       80;
        # listen  [::]:80;
        # server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        # frontend
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # reverse proxy to go backend
        location /api/ {
            proxy_pass http://go_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        }

        # health
        location = /nginx-health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
            access_log off;
        }

        location = /health {
            proxy_pass http://go_backend/health;
        }

        error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        # error_page   500 502 503 504  /50x.html;
        # location = /50x.html {
        #     root   /usr/share/nginx/html;
        # }

        error_page 502 503 504 = @backend_down;

        location @backend_down {
            return 502 "Backend service unavailable\n";
            add_header Content-Type text/plain;
            add_header X-Error-Source nginx always;
        }

        location = /404.html {
            root   /usr/share/nginx/html;
            internal;
        }

        access_log /dev/stdout backend_down if=$log_backend_down;
        error_log /dev/stderr;

    }

